[tool.poetry]
name = "youmirror"
version = "0.1.0"
description = "Create a mirror filetree of your favorite youtube videos"
authors = ["wkrettek <warrenkrettek@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
pytube = "^12.0.0"
ujson = "^5.2.0"
typer = "^0.4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
