default_resolution = "best"
captions = [ "en", "a.en",]
[[channels]]
name = "Videogamedunkey"
url = "https://www.youtube.com/user/videogamedunkey"
default_resolution = "480p"

[[playlists]]
name = "Pepe Prawn"
url = "https://www.youtube.com/playlist?list=PLBZw8Bdva63UAhbdAlbbYotegKhUMeSzN"

[[singles]]
name = "Prawns From Space"
url = "https://www.youtube.com/watch?v=Pa_HT9vQiLw"
locked = "true"

[[singles]]
url = "https://www.youtube.com/watch?v=x2AQp_B-keY"

[[singles]]
url = "https://www.youtube.com/watch?v=RZd_seybEPs"

[[singles]]
name = "Shake it bake it booty quake it"
url = "https://www.youtube.com/watch?v=1AYRsx-l5W4"

[[singles]]
url = "https://www.youtube.com/watch?v=ZmCp8rvXbdU"

